### PR TITLE
added new invoke-d365dmfinit function

### PR DESCRIPTION
**Pull request by gertvdh**
this to trigger the data entity refresh for example

### CODE REVIEW

**Comment by Splaxi** [comment]
Thanks!

Just ignore the errors for now 😉

**Comment by Splaxi** [comment]
Could you explain what it does? 

Is it the same as clicking refresh entities inside d365fo?

**Comment by gertvdh** [comment]
it's similar to hitting the refresh entities button indeed :)

**Comment by Splaxi** [comment]
That is awesome! Makes deployment to Tier2 even more automated!

How did you stumble upon this?!

**Comment by gertvdh** [comment]
we had some custom code in finops first that we called and we wanted to get rid of that. Found it by accident by looking at those importfrompackage calls from https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/data-management-api and compared that with logic behind the refresh button

**Pull request merged**
